# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'link_track.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_linkTrack(object):
    def setupUi(self, linkTrack):
        linkTrack.setObjectName(_fromUtf8("linkTrack"))
        linkTrack.resize(460, 596)
        self.verticalLayout_4 = QtGui.QVBoxLayout(linkTrack)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.splitter_2 = QtGui.QSplitter(linkTrack)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName(_fromUtf8("splitter_2"))
        self.layoutWidget = QtGui.QWidget(self.splitter_2)
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_2 = QtGui.QLabel(self.layoutWidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_4.addWidget(self.label_2)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.tableWidget = QtGui.QTableWidget(self.layoutWidget)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(1)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget.setItem(0, 2, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget.setItem(0, 3, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.tableWidget.setItem(0, 4, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(60)
        self.verticalLayout.addWidget(self.tableWidget)
        self.splitter = QtGui.QSplitter(self.splitter_2)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.layoutWidget1 = QtGui.QWidget(self.splitter)
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_3 = QtGui.QLabel(self.layoutWidget1)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_5.addWidget(self.label_3)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.stackListWidget = QtGui.QListWidget(self.layoutWidget1)
        self.stackListWidget.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.stackListWidget.setObjectName(_fromUtf8("stackListWidget"))
        self.verticalLayout_2.addWidget(self.stackListWidget)
        self.layoutWidget2 = QtGui.QWidget(self.splitter)
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_4 = QtGui.QLabel(self.layoutWidget2)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_6.addWidget(self.label_4)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.mvtTableWidget = QtGui.QTableWidget(self.layoutWidget2)
        self.mvtTableWidget.setObjectName(_fromUtf8("mvtTableWidget"))
        self.mvtTableWidget.setColumnCount(4)
        self.mvtTableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.mvtTableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.mvtTableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.mvtTableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.mvtTableWidget.setHorizontalHeaderItem(3, item)
        self.mvtTableWidget.horizontalHeader().setDefaultSectionSize(50)
        self.verticalLayout_3.addWidget(self.mvtTableWidget)
        self.verticalLayout_4.addWidget(self.splitter_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.extendCheckBox = QtGui.QCheckBox(linkTrack)
        self.extendCheckBox.setObjectName(_fromUtf8("extendCheckBox"))
        self.horizontalLayout_3.addWidget(self.extendCheckBox)
        spacerItem3 = QtGui.QSpacerItem(37, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.label = QtGui.QLabel(linkTrack)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_3.addWidget(self.label)
        self.axisOrderingComboBox = QtGui.QComboBox(linkTrack)
        self.axisOrderingComboBox.setObjectName(_fromUtf8("axisOrderingComboBox"))
        self.axisOrderingComboBox.addItem(_fromUtf8(""))
        self.axisOrderingComboBox.addItem(_fromUtf8(""))
        self.horizontalLayout_3.addWidget(self.axisOrderingComboBox)
        self.topOrderingComboBox = QtGui.QComboBox(linkTrack)
        self.topOrderingComboBox.setObjectName(_fromUtf8("topOrderingComboBox"))
        self.topOrderingComboBox.addItem(_fromUtf8(""))
        self.topOrderingComboBox.addItem(_fromUtf8(""))
        self.horizontalLayout_3.addWidget(self.topOrderingComboBox)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_5 = QtGui.QLabel(linkTrack)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout.addWidget(self.label_5)
        self.zOrderingComboBox = QtGui.QComboBox(linkTrack)
        self.zOrderingComboBox.setObjectName(_fromUtf8("zOrderingComboBox"))
        self.zOrderingComboBox.addItem(_fromUtf8(""))
        self.zOrderingComboBox.addItem(_fromUtf8(""))
        self.horizontalLayout.addWidget(self.zOrderingComboBox)
        self.line = QtGui.QFrame(linkTrack)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.horizontalLayout.addWidget(self.line)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.refresh_pushButton = QtGui.QPushButton(linkTrack)
        self.refresh_pushButton.setObjectName(_fromUtf8("refresh_pushButton"))
        self.horizontalLayout.addWidget(self.refresh_pushButton)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.translate_pushButton = QtGui.QPushButton(linkTrack)
        self.translate_pushButton.setObjectName(_fromUtf8("translate_pushButton"))
        self.horizontalLayout_2.addWidget(self.translate_pushButton)
        self.rotate_pushButton = QtGui.QPushButton(linkTrack)
        self.rotate_pushButton.setObjectName(_fromUtf8("rotate_pushButton"))
        self.horizontalLayout_2.addWidget(self.rotate_pushButton)
        self.cancel_pushButton = QtGui.QPushButton(linkTrack)
        self.cancel_pushButton.setObjectName(_fromUtf8("cancel_pushButton"))
        self.horizontalLayout_2.addWidget(self.cancel_pushButton)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.closeButton = QtGui.QPushButton(linkTrack)
        self.closeButton.setObjectName(_fromUtf8("closeButton"))
        self.horizontalLayout_2.addWidget(self.closeButton)
        self.apply_pushButton = QtGui.QPushButton(linkTrack)
        self.apply_pushButton.setObjectName(_fromUtf8("apply_pushButton"))
        self.horizontalLayout_2.addWidget(self.apply_pushButton)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)

        self.retranslateUi(linkTrack)
        QtCore.QMetaObject.connectSlotsByName(linkTrack)

    def retranslateUi(self, linkTrack):
        linkTrack.setWindowTitle(_translate("linkTrack", "link_track", None))
        self.label_2.setText(_translate("linkTrack", "Line to use:", None))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("linkTrack", "New Row", None))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("linkTrack", "name", None))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("linkTrack", "slice", None))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("linkTrack", "use it", None))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("linkTrack", "anchor", None))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("linkTrack", "translate", None))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.label_3.setText(_translate("linkTrack", "Stack to use:", None))
        self.label_4.setText(_translate("linkTrack", "Mvt:", None))
        item = self.mvtTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("linkTrack", "Slice", None))
        item = self.mvtTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("linkTrack", "X mvt", None))
        item = self.mvtTableWidget.horizontalHeaderItem(2)
        item.setText(_translate("linkTrack", "Y mvt", None))
        item = self.mvtTableWidget.horizontalHeaderItem(3)
        item.setText(_translate("linkTrack", "Angle", None))
        self.extendCheckBox.setText(_translate("linkTrack", "Extend canvas", None))
        self.label.setToolTip(_translate("linkTrack", "<html><head/><body><p>For orienting the track I need to know where is the top and bottom of the slice.</p><p>Default is Y axis with top being 0 and bottom max.</p></body></html>", None))
        self.label.setText(_translate("linkTrack", "Orientation:", None))
        self.axisOrderingComboBox.setItemText(0, _translate("linkTrack", "Y axis", None))
        self.axisOrderingComboBox.setItemText(1, _translate("linkTrack", "X axis", None))
        self.topOrderingComboBox.setItemText(0, _translate("linkTrack", "0 at top/right", None))
        self.topOrderingComboBox.setItemText(1, _translate("linkTrack", "0 at bottom/left", None))
        self.label_5.setToolTip(_translate("linkTrack", "<html><head/><body><p>For orienting the track I need to know where is the top and bottom of the slice.</p><p>Default is Y axis with top being 0 and bottom max.</p></body></html>", None))
        self.label_5.setText(_translate("linkTrack", "Track Ordering:", None))
        self.zOrderingComboBox.setItemText(0, _translate("linkTrack", "high Z is above", None))
        self.zOrderingComboBox.setItemText(1, _translate("linkTrack", "low Z is above", None))
        self.refresh_pushButton.setText(_translate("linkTrack", "refresh lists", None))
        self.translate_pushButton.setText(_translate("linkTrack", "translate", None))
        self.rotate_pushButton.setText(_translate("linkTrack", "rotate", None))
        self.cancel_pushButton.setText(_translate("linkTrack", "cancel", None))
        self.closeButton.setText(_translate("linkTrack", "&Close", None))
        self.apply_pushButton.setText(_translate("linkTrack", "Apply", None))

