# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ara_explorer.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ara_explorer(object):
    def setupUi(self, ara_explorer):
        ara_explorer.setObjectName(_fromUtf8("ara_explorer"))
        ara_explorer.resize(443, 574)
        ara_explorer.setMinimumSize(QtCore.QSize(443, 500))
        self.verticalLayout_3 = QtGui.QVBoxLayout(ara_explorer)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.load_frame = QtGui.QFrame(ara_explorer)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.load_frame.sizePolicy().hasHeightForWidth())
        self.load_frame.setSizePolicy(sizePolicy)
        self.load_frame.setMinimumSize(QtCore.QSize(0, 61))
        self.load_frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.load_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.load_frame.setObjectName(_fromUtf8("load_frame"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.load_frame)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.araName_comboBox = QtGui.QComboBox(self.load_frame)
        self.araName_comboBox.setObjectName(_fromUtf8("araName_comboBox"))
        self.horizontalLayout_5.addWidget(self.araName_comboBox)
        self.load_pushButton = QtGui.QPushButton(self.load_frame)
        self.load_pushButton.setMaximumSize(QtCore.QSize(95, 16777215))
        self.load_pushButton.setObjectName(_fromUtf8("load_pushButton"))
        self.horizontalLayout_5.addWidget(self.load_pushButton)
        self.verticalLayout_3.addWidget(self.load_frame)
        self.frame = QtGui.QFrame(ara_explorer)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(0, 80))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.frame)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.statusBarName_checkBox = QtGui.QCheckBox(self.frame)
        self.statusBarName_checkBox.setChecked(True)
        self.statusBarName_checkBox.setObjectName(_fromUtf8("statusBarName_checkBox"))
        self.verticalLayout.addWidget(self.statusBarName_checkBox)
        self.highlightArea_checkBox = QtGui.QCheckBox(self.frame)
        self.highlightArea_checkBox.setChecked(True)
        self.highlightArea_checkBox.setObjectName(_fromUtf8("highlightArea_checkBox"))
        self.verticalLayout.addWidget(self.highlightArea_checkBox)
        self.overlayTemplate_checkBox = QtGui.QCheckBox(self.frame)
        self.overlayTemplate_checkBox.setEnabled(False)
        self.overlayTemplate_checkBox.setChecked(False)
        self.overlayTemplate_checkBox.setObjectName(_fromUtf8("overlayTemplate_checkBox"))
        self.verticalLayout.addWidget(self.overlayTemplate_checkBox)
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.colorise_pushButton = QtGui.QPushButton(self.frame)
        self.colorise_pushButton.setObjectName(_fromUtf8("colorise_pushButton"))
        self.horizontalLayout_3.addWidget(self.colorise_pushButton)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.scale_label = QtGui.QLabel(self.frame)
        self.scale_label.setObjectName(_fromUtf8("scale_label"))
        self.horizontalLayout_3.addWidget(self.scale_label)
        self.scale_doubleSpinBox = QtGui.QDoubleSpinBox(self.frame)
        self.scale_doubleSpinBox.setObjectName(_fromUtf8("scale_doubleSpinBox"))
        self.horizontalLayout_3.addWidget(self.scale_doubleSpinBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(self.frame)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.showBregma_checkBox = QtGui.QCheckBox(self.frame)
        self.showBregma_checkBox.setObjectName(_fromUtf8("showBregma_checkBox"))
        self.horizontalLayout.addWidget(self.showBregma_checkBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.z_label = QtGui.QLabel(self.frame)
        self.z_label.setObjectName(_fromUtf8("z_label"))
        self.horizontalLayout_2.addWidget(self.z_label)
        self.z_spinBox = QtGui.QSpinBox(self.frame)
        self.z_spinBox.setMaximum(99999)
        self.z_spinBox.setObjectName(_fromUtf8("z_spinBox"))
        self.horizontalLayout_2.addWidget(self.z_spinBox)
        self.x_label = QtGui.QLabel(self.frame)
        self.x_label.setObjectName(_fromUtf8("x_label"))
        self.horizontalLayout_2.addWidget(self.x_label)
        self.x_spinBox = QtGui.QSpinBox(self.frame)
        self.x_spinBox.setMaximum(99999)
        self.x_spinBox.setObjectName(_fromUtf8("x_spinBox"))
        self.horizontalLayout_2.addWidget(self.x_spinBox)
        self.y_label = QtGui.QLabel(self.frame)
        self.y_label.setObjectName(_fromUtf8("y_label"))
        self.horizontalLayout_2.addWidget(self.y_label)
        self.y_spinBox = QtGui.QSpinBox(self.frame)
        self.y_spinBox.setMaximum(99999)
        self.y_spinBox.setObjectName(_fromUtf8("y_spinBox"))
        self.horizontalLayout_2.addWidget(self.y_spinBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addWidget(self.frame)
        self.brainArea_treeView = QtGui.QTreeView(ara_explorer)
        self.brainArea_treeView.setObjectName(_fromUtf8("brainArea_treeView"))
        self.verticalLayout_3.addWidget(self.brainArea_treeView)
        self.scale_label.setBuddy(self.scale_doubleSpinBox)
        self.z_label.setBuddy(self.z_spinBox)
        self.x_label.setBuddy(self.x_spinBox)
        self.y_label.setBuddy(self.y_spinBox)

        self.retranslateUi(ara_explorer)
        QtCore.QMetaObject.connectSlotsByName(ara_explorer)

    def retranslateUi(self, ara_explorer):
        ara_explorer.setWindowTitle(_translate("ara_explorer", "Form", None))
        self.load_pushButton.setText(_translate("ara_explorer", "Load", None))
        self.statusBarName_checkBox.setText(_translate("ara_explorer", "show name in status bar", None))
        self.highlightArea_checkBox.setText(_translate("ara_explorer", "highlight area", None))
        self.overlayTemplate_checkBox.setText(_translate("ara_explorer", "overlay template", None))
        self.colorise_pushButton.setText(_translate("ara_explorer", "colorise", None))
        self.scale_label.setText(_translate("ara_explorer", "Scale:", None))
        self.label.setText(_translate("ara_explorer", "Bregma:", None))
        self.showBregma_checkBox.setText(_translate("ara_explorer", "show", None))
        self.z_label.setText(_translate("ara_explorer", "Z:", None))
        self.x_label.setText(_translate("ara_explorer", "X:", None))
        self.y_label.setText(_translate("ara_explorer", "Y:", None))

